### ISSUE TITLE
Updating NumPy selector

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/orange3-feedstock#18]
We are rapidly approaching a NumPy 1.12 release. May want to update the selector so that it doesn't skip that accidentally.

**Comment by astaric** [comment]
Before we can do this, we need to make sure that our dependencies are built for numpy 1.12.
- [x] scikit-learn (https://github.com/conda-forge/scikit-learn-feedstock/pull/33)
- [ ] bottleneck (https://github.com/conda-forge/bottleneck-feedstock/pull/8)

**Comment by astaric** [comment]
Numpy 1.12 support was added in #21.
